# This script tests the model generated by the train.py on the images in the data directory

# -- Imports --

import os
import tensorflow as tf
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image, ImageOps
from numpy import asarray


# -- Load the test data --

# Define variables
image_directory = 'data/images/'
mask_directory = 'data/masks/'

image_extension = 'jpg'
mask_extension = 'tiff'

WIDTH = 256
HEIGHT = 192
image_dataset = []
mask_dataset = []

print("Loading images ...")

# Load images and masks
masks = sorted(os.listdir(mask_directory))
for i, file_name in enumerate(masks):
    if file_name.endswith(mask_extension):
        image = Image.open(image_directory + file_name.replace(mask_extension, image_extension))
        mask = Image.open(mask_directory + file_name)

        # Resize the image
        scaled_image = ImageOps.fit(image, (WIDTH, HEIGHT), Image.ANTIALIAS)
        # Convert it back to an array
        scaled_image_array = asarray(scaled_image)
        scaled_image_array = scaled_image_array.astype('float32')
        # Scale the pixel values to lie between 0 and 1
        scaled_image_array /= 255.0

        # Resize the mask
        scaled_mask = ImageOps.fit(mask, (WIDTH, HEIGHT), Image.ANTIALIAS)
        # Convert it back to an array
        scaled_mask_array = asarray(scaled_mask)
        scaled_mask_array = scaled_mask_array.astype('float32')
        # Scale the pixel values to lie between 0 and 1
        scaled_mask_array /= 255.0

        # Show image and mask (for debug purposes)
        # plt.figure(figsize=(12, 8))
        # plt.subplot(121)
        # plt.title('scaled_image_array')
        # plt.imshow(scaled_image_array)
        # plt.subplot(122)
        # plt.title('scaled_mask_array')
        # plt.imshow(scaled_mask_array)
        # plt.show()

        image_dataset.append(np.array(scaled_image_array))
        mask_dataset.append(np.array(scaled_mask_array))

X_test, y_test = image_dataset, mask_dataset

print("Done!")


# -- Load model and predict --

print("Loading model ...")

# Load the model with its weights
model = tf.keras.models.load_model('models/keras')

print("Done!")

# Format variables
X_test = np.asarray(X_test)
y_test = np.asarray(y_test)

print("Predicting ...")

# Predict
y_pred = model.predict(X_test)


# --Display the results

for i in range(0, len(y_pred)):
    plt.figure(figsize=(12, 8))
    plt.subplot(131)
    plt.title('X_test example')
    plt.imshow(X_test[i])
    plt.subplot(132)
    plt.title('y_pred example')
    plt.imshow(y_pred[i])
    plt.subplot(133)
    plt.title('y_test example')
    plt.imshow(y_test[i])
    plt.show()

print("Done!")
